CREATE TABLE IF NOT EXISTS CONTACORRENTE (
    ID TEXT PRIMARY KEY,
    NUMEROCONTA TEXT NOT NULL UNIQUE,
    CPF TEXT NOT NULL UNIQUE,
    NOME TEXT NOT NULL,
    SENHAHASH TEXT NOT NULL,
    ATIVO INTEGER NOT NULL DEFAULT 1,
    CRIADOEM TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS MOVIMENTO (
    ID TEXT PRIMARY KEY,
    IDREQUISICAO TEXT NOT NULL UNIQUE,
    NUMEROCONTA TEXT NOT NULL,
    VALOR REAL NOT NULL,
    TIPO TEXT NOT NULL,
    CRIADOEM TEXT NOT NULL,
    FOREIGN KEY (NUMEROCONTA) REFERENCES CONTACORRENTE(NUMEROCONTA)
);
